### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ruipimentel** [adamvoss/languagetool-languageserver#5]
I got errors while trying to build following the instructions of Issue #1.

```shell
rui@mypc ~/Downloads/languagetool-languageserver $ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rui/Downloads/languagetool-languageserver/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'languagetool-languageserver'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.534 secs
```

```shell
rui@mypc ~/Downloads/languagetool-languageserver $ gradle build --info
Starting Build
Settings evaluated using settings file '/home/rui/Downloads/languagetool-languageserver/settings.gradle'.
Projects loaded. Root project using build file '/home/rui/Downloads/languagetool-languageserver/build.gradle'.
Included projects: [root project 'languagetool-languageserver']
Evaluating root project 'languagetool-languageserver' using build file '/home/rui/Downloads/languagetool-languageserver/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rui/Downloads/languagetool-languageserver/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'languagetool-languageserver'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 1.554 secs
```

```shell
rui@mypc ~/Downloads/languagetool-languageserver $ gradle build --debug
10:11:51.777 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventRenderer@7608d498, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@3dbd83b2, org.gradle.logging.internal.JavaUtilLoggingConfigurer@65113ac8]
10:11:52.323 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventRenderer@7608d498, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@3dbd83b2, org.gradle.logging.internal.JavaUtilLoggingConfigurer@65113ac8]
10:11:52.328 [INFO] [org.gradle.BuildLogger] Starting Build
10:11:52.328 [DEBUG] [org.gradle.BuildLogger] Gradle user home: /home/rui/.gradle
10:11:52.329 [DEBUG] [org.gradle.BuildLogger] Current dir: /home/rui/Downloads/languagetool-languageserver
10:11:52.330 [DEBUG] [org.gradle.BuildLogger] Settings file: null
10:11:52.331 [DEBUG] [org.gradle.BuildLogger] Build file: null
10:11:52.348 [DEBUG] [org.gradle.initialization.BuildSourceBuilder] Starting to build the build sources.
10:11:52.349 [DEBUG] [org.gradle.initialization.BuildSourceBuilder] Gradle source dir does not exist. We leave.
10:11:52.351 [DEBUG] [org.gradle.initialization.DefaultGradlePropertiesLoader] Found env project properties: []
10:11:52.352 [DEBUG] [org.gradle.initialization.DefaultGradlePropertiesLoader] Found system project properties: []
10:11:52.446 [DEBUG] [org.gradle.api.internal.artifacts.mvnsettings.DefaultLocalMavenRepositoryLocator] No local repository in Settings file defined. Using default path:
/home/rui/.m2/repository
10:11:52.653 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on buildscript class cache for settings file '/home/rui/Downloads/l
anguagetool-languageserver/settings.gradle' (/home/rui/.gradle/caches/1.4/scripts/settings_372brhii3ufalru1lqp9a4ua2r/SettingsScript/buildscript).
10:11:52.657 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
10:11:52.730 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventR
enderer@7608d498, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@3dbd83b2, org.gradle.logging.internal.JavaUtilLoggingConfigurer@65113ac8]
10:11:52.740 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on no_buildscript class cache for settings file '/home/rui/Download
s/languagetool-languageserver/settings.gradle' (/home/rui/.gradle/caches/1.4/scripts/settings_372brhii3ufalru1lqp9a4ua2r/SettingsScript/no_buildscript).
10:11:52.741 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
10:11:52.810 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventR
enderer@7608d498, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@3dbd83b2, org.gradle.logging.internal.JavaUtilLoggingConfigurer@65113ac8]
10:11:52.812 [DEBUG] [org.gradle.initialization.ScriptEvaluatingSettingsProcessor] Timing: Processing settings took: 0.459 secs
10:11:52.814 [INFO] [org.gradle.BuildLogger] Settings evaluated using settings file '/home/rui/Downloads/languagetool-languageserver/settings.gradle'.
10:11:52.909 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Looking for project properties from: /home/rui/Downloads/languagetool-languageserver/gr
adle.properties
10:11:52.910 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] project property file does not exists. We continue!
10:11:52.912 [INFO] [org.gradle.BuildLogger] Projects loaded. Root project using build file '/home/rui/Downloads/languagetool-languageserver/build.gradle'.
10:11:52.913 [INFO] [org.gradle.BuildLogger] Included projects: [root project 'languagetool-languageserver']
10:11:52.916 [INFO] [org.gradle.configuration.BuildScriptProcessor] Evaluating root project 'languagetool-languageserver' using build file '/home/rui/Downloads/languageto
ol-languageserver/build.gradle'.
10:11:52.921 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on buildscript class cache for build file '/home/rui/Downloads/lang
uagetool-languageserver/build.gradle' (/home/rui/.gradle/caches/1.4/scripts/build_2p5vg7eq4rmmnf5isc06pgt3kf/ProjectScript/buildscript).
10:11:52.922 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
10:11:53.141 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventR
enderer@7608d498, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@3dbd83b2, org.gradle.logging.internal.JavaUtilLoggingConfigurer@65113ac8]
10:11:53.143 [DEBUG] [org.gradle.configuration.BuildScriptProcessor] Timing: Running the build script took 0.225 secs
10:11:53.154 [ERROR] [org.gradle.BuildExceptionReporter]
10:11:53.155 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:11:53.157 [ERROR] [org.gradle.BuildExceptionReporter]
10:11:53.157 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
10:11:53.158 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/home/rui/Downloads/languagetool-languageserver/build.gradle' line: 11
10:11:53.159 [ERROR] [org.gradle.BuildExceptionReporter]
10:11:53.159 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
10:11:53.160 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'languagetool-languageserver'.
10:11:53.161 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find method jcenter() for arguments [] on repository container.
10:11:53.163 [ERROR] [org.gradle.BuildExceptionReporter]
10:11:53.164 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
10:11:53.165 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'languagetool-languageserver'.
10:11:53.166 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerF
actory.java:54)
10:11:53.166 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.j
ava:116)
10:11:53.167 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
10:11:53.168 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:43)
10:11:53.168 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:466)
10:11:53.169 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:77)
10:11:53.170 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
10:11:53.171 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
10:11:53.171 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$CompositeAction.execute(Actions.java:78)
10:11:53.172 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$TransformingActionAdapter.execute(Actions.java:130)
10:11:53.173 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:442)
10:11:53.173 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:437)
10:11:53.174 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:40)
10:11:53.175 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
10:11:53.176 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
10:11:53.177 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
10:11:53.178 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:38)
10:11:53.179 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExe
cuter.java:39)
10:11:53.180 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExe
cuter.java:25)
10:11:53.181 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
10:11:53.182 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
10:11:53.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.j
ava:201)
10:11:53.184 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.j
ava:174)
10:11:53.185 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
10:11:53.186 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
10:11:53.187 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
10:11:53.188 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
10:11:53.189 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:48)
10:11:53.190 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
10:11:53.190 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:39)
10:11:53.191 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
10:11:53.192 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
10:11:53.192 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
10:11:53.193 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.internal.MissingMethodException: Could not find method jcenter() for arguments [] on re
pository container.
10:11:53.194 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
10:11:53.195 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
10:11:53.195 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
10:11:53.196 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler_Decorated.invokeMethod(Unknown Source)
10:11:53.197 [ERROR] [org.gradle.BuildExceptionReporter]        at build_2p5vg7eq4rmmnf5isc06pgt3kf$_run_closure1_closure2.doCall(/home/rui/Downloads/languagetool-languag
eserver/build.gradle:11)
10:11:53.198 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
10:11:53.199 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
10:11:53.200 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:113)
10:11:53.201 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositor
yContainer.java:76)
10:11:53.202 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.DefaultArtifactRepositoryContainer.configure(DefaultArtifactRepositor
yContainer.java:44)
10:11:53.203 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:50)
10:11:53.204 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
10:11:53.205 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:94)
10:11:53.206 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.initialization.AbstractScriptHandler.repositories(AbstractScriptHandler.java:66
)
10:11:53.207 [ERROR] [org.gradle.BuildExceptionReporter]        at build_2p5vg7eq4rmmnf5isc06pgt3kf$_run_closure1.doCall(/home/rui/Downloads/languagetool-languageserver/b
uild.gradle:10)
10:11:53.208 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
10:11:53.209 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:133)
10:11:53.210 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:94)
10:11:53.211 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.buildscript(AbstractProject.java:901)
10:11:53.212 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.Project$buildscript.call(Unknown Source)
10:11:53.213 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.ProjectScript.buildscript(ProjectScript.groovy:42)
10:11:53.214 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.Script$buildscript.callCurrent(Unknown Source)
10:11:53.215 [ERROR] [org.gradle.BuildExceptionReporter]        at build_2p5vg7eq4rmmnf5isc06pgt3kf.run(/home/rui/Downloads/languagetool-languageserver/build.gradle:9)
10:11:53.216 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerF
actory.java:52)
10:11:53.217 [ERROR] [org.gradle.BuildExceptionReporter]        ... 32 more
10:11:53.218 [ERROR] [org.gradle.BuildExceptionReporter]
10:11:53.219 [LIFECYCLE] [org.gradle.BuildResultLogger]
10:11:53.220 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
10:11:53.221 [LIFECYCLE] [org.gradle.BuildResultLogger]
10:11:53.222 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 1.71 secs
10:11:53.240 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for build file '/home/rui/Downloads/languagetool-languag
eserver/build.gradle' (/home/rui/.gradle/caches/1.4/scripts/build_2p5vg7eq4rmmnf5isc06pgt3kf/ProjectScript/buildscript).
10:11:53.241 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for settings file '/home/rui/Downloads/languagetool-l
anguageserver/settings.gradle' (/home/rui/.gradle/caches/1.4/scripts/settings_372brhii3ufalru1lqp9a4ua2r/SettingsScript/no_buildscript).
10:11:53.242 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for settings file '/home/rui/Downloads/languagetool-lang
uageserver/settings.gradle' (/home/rui/.gradle/caches/1.4/scripts/settings_372brhii3ufalru1lqp9a4ua2r/SettingsScript/buildscript).
10:11:53.245 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventR
enderer@7608d498, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@3dbd83b2, org.gradle.logging.internal.JavaUtilLoggingConfigurer@65113ac8]
```

**Comment by davidlday** [comment]
Please see issue #6.
